behaviors:
  PlayerProxy:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 0.0005
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      memory:
        sequence_length: 32
        memory_size: 128
    reward_signals:
      gail:
        gamma: 0.99
        strength: 0.1
        use_actions: true
        demo_path: Assets/Demonstrations

    behavioral_cloning:
      strength: 1.0
      demo_path: Assets/Demonstrations
      steps: 750000

    max_steps: 750000
    time_horizon: 128
    summary_freq: 10000